name: 'Deploy to GH Pages'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        runs: npm install
      - name: build
        runs: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: dist
