name: 'Deploy to GH Pages'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifact
      - name: check files
        run: ls -R
      # - name: Deploy to GH pages
      #   id: deployment
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .
